### ISSUE TITLE
 Test_Identity doesn't work

### ISSUE THREAD

**Issue by iomeone** [fantunes-ds/Identity#2]
1,Thank you for the great engine.
2,Editor project runs well and can show the scene, but Test_Identity doesn't work for me, it just does not show the scene .
can you check it for me. Thank you very much!

**Comment by fantunes-ds** [comment]
Hi iomeone, 

Test_Identity does indeed not work, we had plans of it being the Game project (and Editor being the Editor project) but we ended up discarding Test_Identity and keeping only the Editor. A good thing could be to remove it completely.

**Comment by iomeone** [comment]
Okay, I understand! Thank you for the reply!
